"""add_auth_fields_to_user

Revision ID: 545e7fe519d5
Revises: f93d2f12f708
Create Date: 2026-02-02 20:06:03.324606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545e7fe519d5'
down_revision: Union[str, Sequence[str], None] = 'f93d2f12f708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hashed_password', sa.String(), nullable=True))
        batch_op.alter_column('telegram_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.alter_column('telegram_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('hashed_password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
