"""Fix schema discrepancies

Revision ID: f93d2f12f708
Revises: 2f8620082508
Create Date: 2026-02-02 18:51:08.110975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93d2f12f708'
down_revision: Union[str, Sequence[str], None] = '2f8620082508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('advance_amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('prepayment_owner',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('NEW', 'CONFIRMED', 'PAID', 'CHECKING_IN', 'CHECKED_IN', 'CANCELLED', 'COMPLETED', name='bookingstatus'),
               existing_nullable=False)

    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('NEW', 'CONFIRMED', 'PAID', 'CHECKING_IN', 'CHECKED_IN', 'CANCELLED', 'COMPLETED', name='bookingstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.alter_column('prepayment_owner',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('advance_amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
